# This file was generated by GoReleaser. DO NOT EDIT.
cask "venn" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b5c896441bc3ff831f8417f19ea07096bcafbb74301ed52e03ef10531624d301"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1a0c381466a0da4fcbabb233f8453d89cc6ee9eafaf6f073e4c60e36ff756bc"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59e41b41d691a806266c60cde35cb084a94aa075ad4aecd13804af578c7dab95"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ff57262cdf30f82ca5c9f21e734b4348c73427b86b53166fb65210de6f492b0"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_amd64.tar.gz"
    end
  end

  name "venn"
  desc "Row-level keyed diff of tabular datasets: files, directories and lake tables"
  homepage "https://github.com/KonMam/venn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "venn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/venn"]
    end
  end

  # No zap stanza required
end
