# This file was generated by GoReleaser. DO NOT EDIT.
cask "venn" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b9280973be6d964735540063b03ae1516c741f988ab0e19e3ded382952abecb3"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cd0deb8f041c779d5180e1690a88636cfde449ac45fe78943e47141c4bbf6fd"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b070fdcd2321edc7d437c2be0d4acbe98bdf1cfe6bbdb48d8d099a22b2933db"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5900d876d42340dff906660ebcaa54674da13a8fb25faadcf4f50621224fe92"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_amd64.tar.gz"
    end
  end

  name "venn"
  desc "Row-level keyed diff of tabular datasets: files, directories and lake tables"
  homepage "https://github.com/KonMam/venn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "venn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/venn"]
    end
  end

  # No zap stanza required
end
