# This file was generated by GoReleaser. DO NOT EDIT.
cask "venn" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "aad07b44439cd187dc677b858ec2ba67d6df63349f7e85b86b62637f9ea5e665"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f605fd48abb460d569cc29a17630bfbd779013f3fb16a64c8cc182123530a6c2"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8643bd165153c7f52598bd592a8bf58ccf2e92d2b392f436d742d1a50d34766"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a14a53d19ded352cd63a8f3ab84901dd72da689e7f4f1673b88aea7a67302b0"
      url "https://github.com/KonMam/venn/releases/download/v#{version}/venn_#{version}_linux_amd64.tar.gz"
    end
  end

  name "venn"
  desc "Row-level keyed diff of tabular datasets: files, directories and lake tables"
  homepage "https://github.com/KonMam/venn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "venn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/venn"]
    end
  end

  # No zap stanza required
end
